name: Flujo de trabajo para generar el .jar y ejecutar los test secuencialmente
on:
  workflow_dispatch:
  push:
    branches: [ arreglosJunio ]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el código
        run: |
          chmod +x gradlew        
          ./gradlew jar
      - run: echo "Muestro el UVUS como se pedía. Coincide con mi nombre de usuario de github ${{ github.repository }}."
      
  Test:
    runs-on: ubuntu-latest
    needs: Build
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test
      - run: echo "Muestro el UVUS como se pedía. Coincide con mi nombre de usuario de github ${{ github.repository }}."
